server:
  port : 8080

spring:
  schema: cot_calc
  datasource:
    url: jdbc:postgresql://localhost:5432/main?currentSchema=${spring.schema}
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging.level.root: INFO