GET http://localhost:8080/interview/getAll

###
POST http://localhost:8080/interview/create
Accept: application/json
Content-Type: application/json;charset=UTF-8
Cache-Control: no-cache

{
  "headr": "Работа мечты для джаваскрипта",
  "description": "Лишь бы не ебланил",
  "level": "нормальный"
}
